apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmaps.yaml

#tbh I dont care about this secrets here, probably will do the same for all 
#this secret sholud be outside of the repo 
secretGenerator:
- name: validator
  literals:
  - KC_CLIENT_ID="python"
  - KC_CLIENT_SECRET="olszak-sie-obrazi-jak-wpisze-tu-cos-smiesznego"
