apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: keycloak
  path: keycloak-patch.yaml

configMapGenerator:
- name: client
  literals:
  - KEYCLOAK_SERVER_URL=https://auth.hms.test
  - REALM_NAME=hms
  - CLIENT_ID=hms-client

# In dev env idk about creds in repo
secretGenerator:
- name: kc-client-config
  literals:
  - KC_CLIENT_ID="python"
  - KC_CLIENT_SECRET="olszak-sie-obrazi-jak-wpisze-tu-cos-smiesznego"

- name: kc-admin-client-config
  literals:
  - KC_CLIENT_ID="admin-cli"
  - KC_CLIENT_SECRET="eryk-sie-obrazi-jak-wpisze-tu-cos-smiesznego"

- name: postgres-credentials-keycloak
  literals:
  - POSTGRES_USER=keycloak
  - POSTGRES_PASSWORD=keycloak
  - POSTGRES_DB=keycloak

- name: postgres-credentials-patients
  literals:
  - POSTGRES_USER=patients
  - POSTGRES_PASSWORD=patients
  - POSTGRES_DB=patients_db

- name: keycloak-credentials
  literals:
  - KEYCLOAK_ADMIN=admin
  - KEYCLOAK_ADMIN_PASSWORD=admin