#TODO: make secret for client id and secret
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator
data:
  KC_CLIENT_ID: "python"
  KC_CLIENT_SECRET: "olszak-sie-obrazi-jak-wpisze-tu-cos-smiesznego"
  KC_URL: "http://keycloak"
  KC_PORT: "8080"
  KC_REALM: "hms"
  SSL: "False"