apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator
  template:
    metadata:
      labels:
        app: validator
    spec:
      containers:
      - name: validator
        image: validator
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: validator
spec:
  selector:
    app: validator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000