apiVersion: v1
kind: ConfigMap
metadata:
  name: kc-client-config
data:
  KC_URL: "http://keycloak"
  KC_PORT: "8080"
  KC_REALM: "hms"
  SSL: "False"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patients-db-configmap
data:
  DB_HOST: "patients-db"
  DB_PORT: "5432"
  DB_NAME: "patients_db"
  DB_USER: "patients"
  DB_PASSWORD: "patients"
