apiVersion: v1
kind: ConfigMap
metadata:
  name: kc-client-config
data:
  KC_URL: "http://keycloak"
  KC_PORT: "8080"
  KC_REALM: "hms"
  SSL: "False"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patients-db-configmap
data:
  DB_HOST: "patients-db"
  DB_PORT: "5432"
  DB_NAME: "patients_db"
  DB_USER: "patients"
  DB_PASSWORD: "patients"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-db-configmap
data:
  DB_HOST: "resources-db"
  DB_PORT: "5432"
  DB_NAME: "resources_db"
  DB_USER: "resources"
  DB_PASSWORD: "resources"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: documents-db-configmap
data:
  MINIO_HOST: "documents-db:9000"
  MINIO_ACCESS_KEY: "4B8QgvrGkyFKElzyUJrN"
  MINIO_SECRET_KEY: "3g3Lpa1aOgwk8CXiimIX8wBnCrSFxgXyLHS5FjmD"
  MINIO_BUCKET_NAME: "documents"
---