apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-db
spec:
  selector:
    matchLabels:
      app: documents-db
  replicas: 1
  template:
    metadata:
      labels:
        app: documents-db
    spec:
      containers:
        - name: documents-db
          image: minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - minio server /data --console-address :9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: documents-db-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documents-db-credentials
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
          - name: documents-db-persistent-storage
            mountPath: /data
          ports:
            - containerPort: 9000
            - containerPort: 9001
      volumes:
      - name: documents-db-persistent-storage
        persistentVolumeClaim:
          claimName: documents-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: documents-db
spec:
  selector:
    app: documents-db
  ports:
    - name: minio-api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi