apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: documents
  template:
    metadata:
      labels:
        app: documents
    spec:
      containers:
      - name: documents
        image: documents
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: kc-client-config
        - secretRef:
            name: kc-client-config
        - configMapRef:
            name: documents-db-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: documents
spec:
  selector:
    app: documents
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003