apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- client.yaml
- keycloak.yaml
- validator.yaml
- patients.yaml
- patients-db.yaml
- documents-db.yaml
- documents.yaml
- resources.yaml
- resources-db.yaml
- kraken.yaml
- postgres.yaml #postgres as StatefulSet in base - for 'prod' ideally would be to have DBs outside of cluster
- configmaps.yaml