apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-db
  template:
    metadata:
      labels:
        app: patients-db
    spec:
      containers:
      - name: patients-db
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-patients
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-patients
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-credentials-patients
                key: POSTGRES_DB
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: init-script-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: patients-db
spec:
  selector:
    app: patients-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-configmap
data:
  init.sql: |
    CREATE TABLE "Patients" (
      "ID_patient" int PRIMARY KEY,
      "First_name" varchar,
      "Last_name" varchar,
      "Date_of_birth" date,
      "Gender" varchar,
      "Contact_number" varchar,
      "Address" varchar
    );

    CREATE TABLE "Medical_History" (
      "ID_entry" int PRIMARY KEY,
      "ID_patient" int,
      "Entry_date" date,
      "Diagnosis" varchar,
      "Description_of_disease_or_health_problem" varchar,
      "Prescribed_medicines" varchar,
      "Doctor_notes" varchar
    );

    CREATE TABLE "Vital_Signs" (
      "ID_measurement" int PRIMARY KEY,
      "ID_patient" int,
      "Date_and_time_of_measurement" timestamp,
      "Blood_pressure" varchar,
      "Pulse" varchar,
      "Body_temperature" varchar,
      "Blood_sugar_level" varchar,
      "Other_medical_parameters" varchar
    );

    ALTER TABLE "Medical_History" ADD FOREIGN KEY ("ID_patient") REFERENCES "Patients" ("ID_patient");

    ALTER TABLE "Vital_Signs" ADD FOREIGN KEY ("ID_patient") REFERENCES "Patients" ("ID_patient");
