apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-db
  template:
    metadata:
      labels:
        app: patients-db
    spec:
      containers:
      - name: patients-db
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        configMap:
          name: init-script-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: patients-db
spec:
  selector:
    app: patients-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script-configmap
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS patientsdb;
    USE patientsdb;
    CREATE TABLE `Patients` (
      `ID_patient` int PRIMARY KEY,
      `First_name` varchar(255),
      `Last_name` varchar(255),
      `Date_of_birth` date,
      `Gender` varchar(255),
      `Contact_number` varchar(255),
      `Address` varchar(255)
    );

    CREATE TABLE `Medical_History` (
      `ID_entry` int PRIMARY KEY,
      `ID_patient` int,
      `Entry_date` date,
      `Diagnosis` varchar(255),
      `Description_of_disease_or_health_problem` varchar(255),
      `Prescribed_medicines` varchar(255),
      `Doctor_notes` varchar(255)
    );

    CREATE TABLE `Vital_Signs` (
      `ID_measurement` int PRIMARY KEY,
      `ID_patient` int,
      `Date_and_time_of_measurement` datetime,
      `Blood_pressure` varchar(255),
      `Pulse` varchar(255),
      `Body_temperature` varchar(255),
      `Blood_sugar_level` varchar(255),
      `Other_medical_parameters` varchar(255)
    );

    ALTER TABLE `Medical_History` ADD FOREIGN KEY (`ID_patient`) REFERENCES `Patients` (`ID_patient`);

    ALTER TABLE `Vital_Signs` ADD FOREIGN KEY (`ID_patient`) REFERENCES `Patients` (`ID_patient`);

