apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients
  template:
    metadata:
      labels:
        app: patients
    spec:
      containers:
      - name: patients
        image: patients
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: kc-client-config
        - configMapRef:
            name: patients-db-configmap
        - secretRef:
            name: kc-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: patients
spec:
  selector:
    app: patients
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001