apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources
  template:
    metadata:
      labels:
        app: resources
    spec:
      containers:
      - name: resources
        image: resources
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: kc-client-config
        - secretRef:
            name: kc-client-config
        - configMapRef:
            name: resources-db-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: resources
spec:
  selector:
    app: resources
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002